### 4. 添加检测样品组
POST http://localhost:8080/api/test-sample-groups/6
Content-Type: application/json

{
  "sampleNumber": "YP001",
  "sampleType": "钢筋",
  "jointType": "闪光对焊",
  "rebarGrade": "HRB400",
  "jointGrade": "I级",
  "nominalDiameter": 16.0,
  "furnaceBatchNumber": "LH2023001",
  "manufacturer": "XX钢铁厂",
  "representativeQuantity": "100个",
  "sampleStatus": "合格",
  "weldingMethod": "电弧焊",
  "welderName": "张三",
  "welderCertificateNumber": "HGZ001",
  "testResults": [
    {
      "testingBasis": "GB/T 228.1-2021",
      "testItemSettingId": 130,
      "technicalRequirements": "屈服强度≥400MPa",
      "bendingHeadDiameter": null,
      "bendingAngle": null
    },
    {
      "testingBasis": "GB/T 232-2010",
      "testItemSettingId": 135,
      "technicalRequirements": "弯曲90度无裂纹",
      "bendingHeadDiameter": 50.0,
      "bendingAngle": 90.0
    }
  ]
}

### 5. 修改检测样品组
PUT http://localhost:8080/api/test-sample-groups/3
Content-Type: application/json

{
  "sampleNumber": "YP001-UPDATED",
  "sampleType": "钢筋",
  "jointType": "电渣压力焊",
  "rebarGrade": "HRB500",
  "jointGrade": "II级",
  "nominalDiameter": 18.0,
  "furnaceBatchNumber": "LH2023002",
  "manufacturer": "YY钢铁厂",
  "representativeQuantity": "120个",
  "sampleStatus": "待检",
  "weldingMethod": "手工电弧焊",
  "welderName": "李四",
  "welderCertificateNumber": "HGZ002",
  "testResults": [
    {
      "id": 3,
      "testingBasis": "GB/T 228.1-2021-UPDATED",
      "testItemSettingId": 130,
      "technicalRequirements": "抗拉强度≥600MPa",
      "bendingHeadDiameter": null,
      "bendingAngle": null
    },
    {
      "id": 4,
      "testingBasis": "GB/T 232-2010-UPDATED",
      "testItemSettingId": 135,
      "technicalRequirements": "反向弯曲180度无裂纹",
      "bendingHeadDiameter": 60.0,
      "bendingAngle": 180.0
    },
    {
      "testingBasis": "新增加的检测依据",
      "testItemSettingId": 178,
      "technicalRequirements": "新增加的技术要求",
      "bendingHeadDiameter": null,
      "bendingAngle": null
    }
  ]
}

### 6. 删除检测样品组
DELETE http://localhost:8080/api/test-sample-groups/4